bind = $mainMod, SPACE, exec, $menu

bind = $mainMod, return, exec, $terminal
bind = $mainMod CTRL, W, exec, $terminal impala
bind = $mainMod CTRL, B, exec, $terminal bluetui
bind = $mainMod CTRL, A, exec, $terminal ncpamixer
bind = $mainMod CTRL, E, exec, $terminal yazi
bind = $mainMod CTRL, S, exec, $terminal nudoku
bind = $mainMod CTRL, D, exec, $terminal dua i
bind = $mainMod CTRL, G, exec, $terminal amdgpu_top --dark

bind = $mainMod CTRL SHIFT, D, exec, $terminal dua i /

bind = $mainMod SHIFT, E, exec, dolphin
bind = $mainMod, C, exec, code
bind = $mainMod, G, exec, chromium
