bind = $mainMod, code:34, layoutmsg, focusmaster master # [

bind = $mainMod, P, layoutmsg, cyclenext
bind = $mainMod, U, layoutmsg, cycleprev

# shift window
bind = $mainMod SHIFT, code:34, layoutmsg, swapwithmaster master # SHIFT + [

bind = $mainMod SHIFT, P, layoutmsg, swapnext
bind = $mainMod SHIFT, U, layoutmsg, swapprev

bind = $mainMod, Tab, exec, ~/.config/hypr/scripts/toggle_layout.sh
bind = $mainMod CTRL, Tab, exec, ~/.config/hypr/scripts/toggle_resolution.sh
