bind = $mainMod, Q, killactive,
bind = $mainMod, P, pseudo,
bind = $mainMod, BACKSPACE, exec, ags request toggle-power-menu
bind = $mainMod CTRL, BACKSPACE, exec, hyprlock
bind = $mainMod, Delete, exit,
bind = $mainMod ALT, K, exec, hyprctl switchxkblayout all next

source=~/.config/hypr/keybindings/window.conf
source=~/.config/hypr/keybindings/workspace.conf
source=~/.config/hypr/keybindings/multimedia.conf
source=~/.config/hypr/keybindings/applications.conf
source=~/.config/hypr/keybindings/layout.conf

source=~/.config/hypr/keybindings/tools.conf
