# Steam/Discord auth popups
windowrulev2 = float,title:^(Sign in to Steam|Discord Updater)$
windowrulev2 = opacity 0.45 0.45,title:^(Sign in to Steam|Discord Updater)$
windowrulev2 = move 100%-w-16 100%-h-16,title:^(Sign in to Steam|Discord Updater)$

# Steam
windowrulev2 = opacity 0.95 0.95,class:^(steam)$
windowrulev2 = workspace 9,class:^(steam)$

# Discord
windowrulev2 = opacity 0.95 0.95,class:^(discord)$
windowrulev2 = workspace special:magic,class:^(discord)$
